apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bup6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-bup6@sha256:9533169dab63a6116769fff44e4000ff604ec165e2a5b9ea3c8a5c64c0e9d51a
        name: my-nodejs
        resources: {}
status: {}
